// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/timesheet/v1/timesheet.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimesheetItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EmployeeId    uint32                 `protobuf:"varint,2,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	MonthYear     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=month_year,json=monthYear,proto3" json:"month_year,omitempty"`
	WorkingDays   int32                  `protobuf:"varint,4,opt,name=working_days,json=workingDays,proto3" json:"working_days,omitempty"`
	OvertimeHours float64                `protobuf:"fixed64,5,opt,name=overtime_hours,json=overtimeHours,proto3" json:"overtime_hours,omitempty"`
	LeaveDays     int32                  `protobuf:"varint,6,opt,name=leave_days,json=leaveDays,proto3" json:"leave_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimesheetItem) Reset() {
	*x = TimesheetItem{}
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimesheetItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimesheetItem) ProtoMessage() {}

func (x *TimesheetItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimesheetItem.ProtoReflect.Descriptor instead.
func (*TimesheetItem) Descriptor() ([]byte, []int) {
	return file_api_timesheet_v1_timesheet_proto_rawDescGZIP(), []int{0}
}

func (x *TimesheetItem) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TimesheetItem) GetEmployeeId() uint32 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *TimesheetItem) GetMonthYear() *timestamppb.Timestamp {
	if x != nil {
		return x.MonthYear
	}
	return nil
}

func (x *TimesheetItem) GetWorkingDays() int32 {
	if x != nil {
		return x.WorkingDays
	}
	return 0
}

func (x *TimesheetItem) GetOvertimeHours() float64 {
	if x != nil {
		return x.OvertimeHours
	}
	return 0
}

func (x *TimesheetItem) GetLeaveDays() int32 {
	if x != nil {
		return x.LeaveDays
	}
	return 0
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_timesheet_v1_timesheet_proto_rawDescGZIP(), []int{1}
}

func (x *ListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TimesheetItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReply) Reset() {
	*x = ListReply{}
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReply) ProtoMessage() {}

func (x *ListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReply.ProtoReflect.Descriptor instead.
func (*ListReply) Descriptor() ([]byte, []int) {
	return file_api_timesheet_v1_timesheet_proto_rawDescGZIP(), []int{2}
}

func (x *ListReply) GetItems() []*TimesheetItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListReply) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_timesheet_v1_timesheet_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *TimesheetItem         `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReply) Reset() {
	*x = GetReply{}
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReply) ProtoMessage() {}

func (x *GetReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReply.ProtoReflect.Descriptor instead.
func (*GetReply) Descriptor() ([]byte, []int) {
	return file_api_timesheet_v1_timesheet_proto_rawDescGZIP(), []int{4}
}

func (x *GetReply) GetItem() *TimesheetItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    uint32                 `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	MonthYear     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=month_year,json=monthYear,proto3" json:"month_year,omitempty"`
	WorkingDays   int32                  `protobuf:"varint,3,opt,name=working_days,json=workingDays,proto3" json:"working_days,omitempty"`
	OvertimeHours float64                `protobuf:"fixed64,4,opt,name=overtime_hours,json=overtimeHours,proto3" json:"overtime_hours,omitempty"`
	LeaveDays     int32                  `protobuf:"varint,5,opt,name=leave_days,json=leaveDays,proto3" json:"leave_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_api_timesheet_v1_timesheet_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRequest) GetEmployeeId() uint32 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *CreateRequest) GetMonthYear() *timestamppb.Timestamp {
	if x != nil {
		return x.MonthYear
	}
	return nil
}

func (x *CreateRequest) GetWorkingDays() int32 {
	if x != nil {
		return x.WorkingDays
	}
	return 0
}

func (x *CreateRequest) GetOvertimeHours() float64 {
	if x != nil {
		return x.OvertimeHours
	}
	return 0
}

func (x *CreateRequest) GetLeaveDays() int32 {
	if x != nil {
		return x.LeaveDays
	}
	return 0
}

type CreateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *TimesheetItem         `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReply) Reset() {
	*x = CreateReply{}
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReply) ProtoMessage() {}

func (x *CreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReply.ProtoReflect.Descriptor instead.
func (*CreateReply) Descriptor() ([]byte, []int) {
	return file_api_timesheet_v1_timesheet_proto_rawDescGZIP(), []int{6}
}

func (x *CreateReply) GetItem() *TimesheetItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EmployeeId    uint32                 `protobuf:"varint,2,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	MonthYear     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=month_year,json=monthYear,proto3" json:"month_year,omitempty"`
	WorkingDays   int32                  `protobuf:"varint,4,opt,name=working_days,json=workingDays,proto3" json:"working_days,omitempty"`
	OvertimeHours float64                `protobuf:"fixed64,5,opt,name=overtime_hours,json=overtimeHours,proto3" json:"overtime_hours,omitempty"`
	LeaveDays     int32                  `protobuf:"varint,6,opt,name=leave_days,json=leaveDays,proto3" json:"leave_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_timesheet_v1_timesheet_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRequest) GetEmployeeId() uint32 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *UpdateRequest) GetMonthYear() *timestamppb.Timestamp {
	if x != nil {
		return x.MonthYear
	}
	return nil
}

func (x *UpdateRequest) GetWorkingDays() int32 {
	if x != nil {
		return x.WorkingDays
	}
	return 0
}

func (x *UpdateRequest) GetOvertimeHours() float64 {
	if x != nil {
		return x.OvertimeHours
	}
	return 0
}

func (x *UpdateRequest) GetLeaveDays() int32 {
	if x != nil {
		return x.LeaveDays
	}
	return 0
}

type UpdateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *TimesheetItem         `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReply) Reset() {
	*x = UpdateReply{}
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReply) ProtoMessage() {}

func (x *UpdateReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReply.ProtoReflect.Descriptor instead.
func (*UpdateReply) Descriptor() ([]byte, []int) {
	return file_api_timesheet_v1_timesheet_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateReply) GetItem() *TimesheetItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_timesheet_v1_timesheet_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReply) Reset() {
	*x = DeleteReply{}
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReply) ProtoMessage() {}

func (x *DeleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReply.ProtoReflect.Descriptor instead.
func (*DeleteReply) Descriptor() ([]byte, []int) {
	return file_api_timesheet_v1_timesheet_proto_rawDescGZIP(), []int{10}
}

var File_api_timesheet_v1_timesheet_proto protoreflect.FileDescriptor

const file_api_timesheet_v1_timesheet_proto_rawDesc = "" +
	"\n" +
	" api/timesheet/v1/timesheet.proto\x12\ftimesheet.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe4\x01\n" +
	"\rTimesheetItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1f\n" +
	"\vemployee_id\x18\x02 \x01(\rR\n" +
	"employeeId\x129\n" +
	"\n" +
	"month_year\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tmonthYear\x12!\n" +
	"\fworking_days\x18\x04 \x01(\x05R\vworkingDays\x12%\n" +
	"\x0eovertime_hours\x18\x05 \x01(\x01R\rovertimeHours\x12\x1d\n" +
	"\n" +
	"leave_days\x18\x06 \x01(\x05R\tleaveDays\"I\n" +
	"\vListRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"f\n" +
	"\tListReply\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.timesheet.v1.TimesheetItemR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\";\n" +
	"\bGetReply\x12/\n" +
	"\x04item\x18\x01 \x01(\v2\x1b.timesheet.v1.TimesheetItemR\x04item\"\xd4\x01\n" +
	"\rCreateRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\rR\n" +
	"employeeId\x129\n" +
	"\n" +
	"month_year\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tmonthYear\x12!\n" +
	"\fworking_days\x18\x03 \x01(\x05R\vworkingDays\x12%\n" +
	"\x0eovertime_hours\x18\x04 \x01(\x01R\rovertimeHours\x12\x1d\n" +
	"\n" +
	"leave_days\x18\x05 \x01(\x05R\tleaveDays\">\n" +
	"\vCreateReply\x12/\n" +
	"\x04item\x18\x01 \x01(\v2\x1b.timesheet.v1.TimesheetItemR\x04item\"\xe4\x01\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1f\n" +
	"\vemployee_id\x18\x02 \x01(\rR\n" +
	"employeeId\x129\n" +
	"\n" +
	"month_year\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tmonthYear\x12!\n" +
	"\fworking_days\x18\x04 \x01(\x05R\vworkingDays\x12%\n" +
	"\x0eovertime_hours\x18\x05 \x01(\x01R\rovertimeHours\x12\x1d\n" +
	"\n" +
	"leave_days\x18\x06 \x01(\x05R\tleaveDays\">\n" +
	"\vUpdateReply\x12/\n" +
	"\x04item\x18\x01 \x01(\v2\x1b.timesheet.v1.TimesheetItemR\x04item\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\r\n" +
	"\vDeleteReply2\xc4\x03\n" +
	"\tTimesheet\x12O\n" +
	"\x04List\x12\x19.timesheet.v1.ListRequest\x1a\x17.timesheet.v1.ListReply\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/timesheets\x12Q\n" +
	"\x03Get\x12\x18.timesheet.v1.GetRequest\x1a\x16.timesheet.v1.GetReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/timesheets/{id}\x12X\n" +
	"\x06Create\x12\x1b.timesheet.v1.CreateRequest\x1a\x19.timesheet.v1.CreateReply\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/timesheets\x12]\n" +
	"\x06Update\x12\x1b.timesheet.v1.UpdateRequest\x1a\x19.timesheet.v1.UpdateReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/timesheets/{id}\x12Z\n" +
	"\x06Delete\x12\x1b.timesheet.v1.DeleteRequest\x1a\x19.timesheet.v1.DeleteReply\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/timesheets/{id}B\x1bZ\x19myapp/api/timesheet/v1;v1b\x06proto3"

var (
	file_api_timesheet_v1_timesheet_proto_rawDescOnce sync.Once
	file_api_timesheet_v1_timesheet_proto_rawDescData []byte
)

func file_api_timesheet_v1_timesheet_proto_rawDescGZIP() []byte {
	file_api_timesheet_v1_timesheet_proto_rawDescOnce.Do(func() {
		file_api_timesheet_v1_timesheet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_timesheet_v1_timesheet_proto_rawDesc), len(file_api_timesheet_v1_timesheet_proto_rawDesc)))
	})
	return file_api_timesheet_v1_timesheet_proto_rawDescData
}

var file_api_timesheet_v1_timesheet_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_timesheet_v1_timesheet_proto_goTypes = []any{
	(*TimesheetItem)(nil),         // 0: timesheet.v1.TimesheetItem
	(*ListRequest)(nil),           // 1: timesheet.v1.ListRequest
	(*ListReply)(nil),             // 2: timesheet.v1.ListReply
	(*GetRequest)(nil),            // 3: timesheet.v1.GetRequest
	(*GetReply)(nil),              // 4: timesheet.v1.GetReply
	(*CreateRequest)(nil),         // 5: timesheet.v1.CreateRequest
	(*CreateReply)(nil),           // 6: timesheet.v1.CreateReply
	(*UpdateRequest)(nil),         // 7: timesheet.v1.UpdateRequest
	(*UpdateReply)(nil),           // 8: timesheet.v1.UpdateReply
	(*DeleteRequest)(nil),         // 9: timesheet.v1.DeleteRequest
	(*DeleteReply)(nil),           // 10: timesheet.v1.DeleteReply
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_api_timesheet_v1_timesheet_proto_depIdxs = []int32{
	11, // 0: timesheet.v1.TimesheetItem.month_year:type_name -> google.protobuf.Timestamp
	0,  // 1: timesheet.v1.ListReply.items:type_name -> timesheet.v1.TimesheetItem
	0,  // 2: timesheet.v1.GetReply.item:type_name -> timesheet.v1.TimesheetItem
	11, // 3: timesheet.v1.CreateRequest.month_year:type_name -> google.protobuf.Timestamp
	0,  // 4: timesheet.v1.CreateReply.item:type_name -> timesheet.v1.TimesheetItem
	11, // 5: timesheet.v1.UpdateRequest.month_year:type_name -> google.protobuf.Timestamp
	0,  // 6: timesheet.v1.UpdateReply.item:type_name -> timesheet.v1.TimesheetItem
	1,  // 7: timesheet.v1.Timesheet.List:input_type -> timesheet.v1.ListRequest
	3,  // 8: timesheet.v1.Timesheet.Get:input_type -> timesheet.v1.GetRequest
	5,  // 9: timesheet.v1.Timesheet.Create:input_type -> timesheet.v1.CreateRequest
	7,  // 10: timesheet.v1.Timesheet.Update:input_type -> timesheet.v1.UpdateRequest
	9,  // 11: timesheet.v1.Timesheet.Delete:input_type -> timesheet.v1.DeleteRequest
	2,  // 12: timesheet.v1.Timesheet.List:output_type -> timesheet.v1.ListReply
	4,  // 13: timesheet.v1.Timesheet.Get:output_type -> timesheet.v1.GetReply
	6,  // 14: timesheet.v1.Timesheet.Create:output_type -> timesheet.v1.CreateReply
	8,  // 15: timesheet.v1.Timesheet.Update:output_type -> timesheet.v1.UpdateReply
	10, // 16: timesheet.v1.Timesheet.Delete:output_type -> timesheet.v1.DeleteReply
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_timesheet_v1_timesheet_proto_init() }
func file_api_timesheet_v1_timesheet_proto_init() {
	if File_api_timesheet_v1_timesheet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_timesheet_v1_timesheet_proto_rawDesc), len(file_api_timesheet_v1_timesheet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_timesheet_v1_timesheet_proto_goTypes,
		DependencyIndexes: file_api_timesheet_v1_timesheet_proto_depIdxs,
		MessageInfos:      file_api_timesheet_v1_timesheet_proto_msgTypes,
	}.Build()
	File_api_timesheet_v1_timesheet_proto = out.File
	file_api_timesheet_v1_timesheet_proto_goTypes = nil
	file_api_timesheet_v1_timesheet_proto_depIdxs = nil
}
