// api/timesheet/v1/timesheet.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/timesheet/v1/timesheet.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTimesheetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    uint32                 `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	WorkDate      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=work_date,json=workDate,proto3" json:"work_date,omitempty"`
	HoursWorked   float64                `protobuf:"fixed64,3,opt,name=hours_worked,json=hoursWorked,proto3" json:"hours_worked,omitempty"`
	OvertimeHours float64                `protobuf:"fixed64,4,opt,name=overtime_hours,json=overtimeHours,proto3" json:"overtime_hours,omitempty"`
	IsLeave       bool                   `protobuf:"varint,5,opt,name=is_leave,json=isLeave,proto3" json:"is_leave,omitempty"`
	LeaveType     string                 `protobuf:"bytes,6,opt,name=leave_type,json=leaveType,proto3" json:"leave_type,omitempty"`
	Note          string                 `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTimesheetRequest) Reset() {
	*x = CreateTimesheetRequest{}
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTimesheetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTimesheetRequest) ProtoMessage() {}

func (x *CreateTimesheetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTimesheetRequest.ProtoReflect.Descriptor instead.
func (*CreateTimesheetRequest) Descriptor() ([]byte, []int) {
	return file_api_timesheet_v1_timesheet_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTimesheetRequest) GetEmployeeId() uint32 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *CreateTimesheetRequest) GetWorkDate() *timestamppb.Timestamp {
	if x != nil {
		return x.WorkDate
	}
	return nil
}

func (x *CreateTimesheetRequest) GetHoursWorked() float64 {
	if x != nil {
		return x.HoursWorked
	}
	return 0
}

func (x *CreateTimesheetRequest) GetOvertimeHours() float64 {
	if x != nil {
		return x.OvertimeHours
	}
	return 0
}

func (x *CreateTimesheetRequest) GetIsLeave() bool {
	if x != nil {
		return x.IsLeave
	}
	return false
}

func (x *CreateTimesheetRequest) GetLeaveType() string {
	if x != nil {
		return x.LeaveType
	}
	return ""
}

func (x *CreateTimesheetRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type CreateTimesheetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTimesheetReply) Reset() {
	*x = CreateTimesheetReply{}
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTimesheetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTimesheetReply) ProtoMessage() {}

func (x *CreateTimesheetReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_timesheet_v1_timesheet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTimesheetReply.ProtoReflect.Descriptor instead.
func (*CreateTimesheetReply) Descriptor() ([]byte, []int) {
	return file_api_timesheet_v1_timesheet_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTimesheetReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_timesheet_v1_timesheet_proto protoreflect.FileDescriptor

const file_api_timesheet_v1_timesheet_proto_rawDesc = "" +
	"\n" +
	" api/timesheet/v1/timesheet.proto\x12\ftimesheet.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x02\n" +
	"\x16CreateTimesheetRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\rR\n" +
	"employeeId\x127\n" +
	"\twork_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bworkDate\x12!\n" +
	"\fhours_worked\x18\x03 \x01(\x01R\vhoursWorked\x12%\n" +
	"\x0eovertime_hours\x18\x04 \x01(\x01R\rovertimeHours\x12\x19\n" +
	"\bis_leave\x18\x05 \x01(\bR\aisLeave\x12\x1d\n" +
	"\n" +
	"leave_type\x18\x06 \x01(\tR\tleaveType\x12\x12\n" +
	"\x04note\x18\a \x01(\tR\x04note\"0\n" +
	"\x14CreateTimesheetReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2z\n" +
	"\tTimesheet\x12m\n" +
	"\x06Create\x12$.timesheet.v1.CreateTimesheetRequest\x1a\".timesheet.v1.CreateTimesheetReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/timesheetsB\x1bZ\x19myapp/api/timesheet/v1;v1b\x06proto3"

var (
	file_api_timesheet_v1_timesheet_proto_rawDescOnce sync.Once
	file_api_timesheet_v1_timesheet_proto_rawDescData []byte
)

func file_api_timesheet_v1_timesheet_proto_rawDescGZIP() []byte {
	file_api_timesheet_v1_timesheet_proto_rawDescOnce.Do(func() {
		file_api_timesheet_v1_timesheet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_timesheet_v1_timesheet_proto_rawDesc), len(file_api_timesheet_v1_timesheet_proto_rawDesc)))
	})
	return file_api_timesheet_v1_timesheet_proto_rawDescData
}

var file_api_timesheet_v1_timesheet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_timesheet_v1_timesheet_proto_goTypes = []any{
	(*CreateTimesheetRequest)(nil), // 0: timesheet.v1.CreateTimesheetRequest
	(*CreateTimesheetReply)(nil),   // 1: timesheet.v1.CreateTimesheetReply
	(*timestamppb.Timestamp)(nil),  // 2: google.protobuf.Timestamp
}
var file_api_timesheet_v1_timesheet_proto_depIdxs = []int32{
	2, // 0: timesheet.v1.CreateTimesheetRequest.work_date:type_name -> google.protobuf.Timestamp
	0, // 1: timesheet.v1.Timesheet.Create:input_type -> timesheet.v1.CreateTimesheetRequest
	1, // 2: timesheet.v1.Timesheet.Create:output_type -> timesheet.v1.CreateTimesheetReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_timesheet_v1_timesheet_proto_init() }
func file_api_timesheet_v1_timesheet_proto_init() {
	if File_api_timesheet_v1_timesheet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_timesheet_v1_timesheet_proto_rawDesc), len(file_api_timesheet_v1_timesheet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_timesheet_v1_timesheet_proto_goTypes,
		DependencyIndexes: file_api_timesheet_v1_timesheet_proto_depIdxs,
		MessageInfos:      file_api_timesheet_v1_timesheet_proto_msgTypes,
	}.Build()
	File_api_timesheet_v1_timesheet_proto = out.File
	file_api_timesheet_v1_timesheet_proto_goTypes = nil
	file_api_timesheet_v1_timesheet_proto_depIdxs = nil
}
