// api/timesheet/v1/timesheet.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/timesheet/v1/timesheet.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Timesheet_Create_FullMethodName = "/timesheet.v1.Timesheet/Create"
)

// TimesheetClient is the client API for Timesheet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TimesheetClient interface {
	Create(ctx context.Context, in *CreateTimesheetRequest, opts ...grpc.CallOption) (*CreateTimesheetReply, error)
}

type timesheetClient struct {
	cc grpc.ClientConnInterface
}

func NewTimesheetClient(cc grpc.ClientConnInterface) TimesheetClient {
	return &timesheetClient{cc}
}

func (c *timesheetClient) Create(ctx context.Context, in *CreateTimesheetRequest, opts ...grpc.CallOption) (*CreateTimesheetReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTimesheetReply)
	err := c.cc.Invoke(ctx, Timesheet_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimesheetServer is the server API for Timesheet service.
// All implementations must embed UnimplementedTimesheetServer
// for forward compatibility.
type TimesheetServer interface {
	Create(context.Context, *CreateTimesheetRequest) (*CreateTimesheetReply, error)
	mustEmbedUnimplementedTimesheetServer()
}

// UnimplementedTimesheetServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTimesheetServer struct{}

func (UnimplementedTimesheetServer) Create(context.Context, *CreateTimesheetRequest) (*CreateTimesheetReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedTimesheetServer) mustEmbedUnimplementedTimesheetServer() {}
func (UnimplementedTimesheetServer) testEmbeddedByValue()                   {}

// UnsafeTimesheetServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimesheetServer will
// result in compilation errors.
type UnsafeTimesheetServer interface {
	mustEmbedUnimplementedTimesheetServer()
}

func RegisterTimesheetServer(s grpc.ServiceRegistrar, srv TimesheetServer) {
	// If the following call panics, it indicates UnimplementedTimesheetServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Timesheet_ServiceDesc, srv)
}

func _Timesheet_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTimesheetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimesheetServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Timesheet_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimesheetServer).Create(ctx, req.(*CreateTimesheetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Timesheet_ServiceDesc is the grpc.ServiceDesc for Timesheet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Timesheet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "timesheet.v1.Timesheet",
	HandlerType: (*TimesheetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Timesheet_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/timesheet/v1/timesheet.proto",
}
