// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.21.12
// source: api/timesheet/v1/timesheet.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTimesheetCreate = "/timesheet.v1.Timesheet/Create"

type TimesheetHTTPServer interface {
	Create(context.Context, *CreateTimesheetRequest) (*CreateTimesheetReply, error)
}

func RegisterTimesheetHTTPServer(s *http.Server, srv TimesheetHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/timesheets", _Timesheet_Create0_HTTP_Handler(srv))
}

func _Timesheet_Create0_HTTP_Handler(srv TimesheetHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTimesheetRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTimesheetCreate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Create(ctx, req.(*CreateTimesheetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateTimesheetReply)
		return ctx.Result(200, reply)
	}
}

type TimesheetHTTPClient interface {
	Create(ctx context.Context, req *CreateTimesheetRequest, opts ...http.CallOption) (rsp *CreateTimesheetReply, err error)
}

type TimesheetHTTPClientImpl struct {
	cc *http.Client
}

func NewTimesheetHTTPClient(client *http.Client) TimesheetHTTPClient {
	return &TimesheetHTTPClientImpl{client}
}

func (c *TimesheetHTTPClientImpl) Create(ctx context.Context, in *CreateTimesheetRequest, opts ...http.CallOption) (*CreateTimesheetReply, error) {
	var out CreateTimesheetReply
	pattern := "/v1/timesheets"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTimesheetCreate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
