// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/payroll/v1/payroll.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculatePayrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    uint32                 `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	WorkingDays   int32                  `protobuf:"varint,2,opt,name=working_days,json=workingDays,proto3" json:"working_days,omitempty"`
	OvertimeHours float64                `protobuf:"fixed64,3,opt,name=overtime_hours,json=overtimeHours,proto3" json:"overtime_hours,omitempty"`
	Allowances    float64                `protobuf:"fixed64,4,opt,name=allowances,proto3" json:"allowances,omitempty"`
	MonthYear     string                 `protobuf:"bytes,5,opt,name=month_year,json=monthYear,proto3" json:"month_year,omitempty"` // Format: YYYY-MM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculatePayrollRequest) Reset() {
	*x = CalculatePayrollRequest{}
	mi := &file_api_payroll_v1_payroll_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePayrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePayrollRequest) ProtoMessage() {}

func (x *CalculatePayrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payroll_v1_payroll_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePayrollRequest.ProtoReflect.Descriptor instead.
func (*CalculatePayrollRequest) Descriptor() ([]byte, []int) {
	return file_api_payroll_v1_payroll_proto_rawDescGZIP(), []int{0}
}

func (x *CalculatePayrollRequest) GetEmployeeId() uint32 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *CalculatePayrollRequest) GetWorkingDays() int32 {
	if x != nil {
		return x.WorkingDays
	}
	return 0
}

func (x *CalculatePayrollRequest) GetOvertimeHours() float64 {
	if x != nil {
		return x.OvertimeHours
	}
	return 0
}

func (x *CalculatePayrollRequest) GetAllowances() float64 {
	if x != nil {
		return x.Allowances
	}
	return 0
}

func (x *CalculatePayrollRequest) GetMonthYear() string {
	if x != nil {
		return x.MonthYear
	}
	return ""
}

type CalculatePayrollReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrossSalary   float64                `protobuf:"fixed64,1,opt,name=gross_salary,json=grossSalary,proto3" json:"gross_salary,omitempty"`
	NetSalary     float64                `protobuf:"fixed64,2,opt,name=net_salary,json=netSalary,proto3" json:"net_salary,omitempty"`
	Deductions    float64                `protobuf:"fixed64,3,opt,name=deductions,proto3" json:"deductions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculatePayrollReply) Reset() {
	*x = CalculatePayrollReply{}
	mi := &file_api_payroll_v1_payroll_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePayrollReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePayrollReply) ProtoMessage() {}

func (x *CalculatePayrollReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_payroll_v1_payroll_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePayrollReply.ProtoReflect.Descriptor instead.
func (*CalculatePayrollReply) Descriptor() ([]byte, []int) {
	return file_api_payroll_v1_payroll_proto_rawDescGZIP(), []int{1}
}

func (x *CalculatePayrollReply) GetGrossSalary() float64 {
	if x != nil {
		return x.GrossSalary
	}
	return 0
}

func (x *CalculatePayrollReply) GetNetSalary() float64 {
	if x != nil {
		return x.NetSalary
	}
	return 0
}

func (x *CalculatePayrollReply) GetDeductions() float64 {
	if x != nil {
		return x.Deductions
	}
	return 0
}

var File_api_payroll_v1_payroll_proto protoreflect.FileDescriptor

const file_api_payroll_v1_payroll_proto_rawDesc = "" +
	"\n" +
	"\x1capi/payroll/v1/payroll.proto\x12\n" +
	"payroll.v1\x1a\x1cgoogle/api/annotations.proto\"\xc3\x01\n" +
	"\x17CalculatePayrollRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\rR\n" +
	"employeeId\x12!\n" +
	"\fworking_days\x18\x02 \x01(\x05R\vworkingDays\x12%\n" +
	"\x0eovertime_hours\x18\x03 \x01(\x01R\rovertimeHours\x12\x1e\n" +
	"\n" +
	"allowances\x18\x04 \x01(\x01R\n" +
	"allowances\x12\x1d\n" +
	"\n" +
	"month_year\x18\x05 \x01(\tR\tmonthYear\"y\n" +
	"\x15CalculatePayrollReply\x12!\n" +
	"\fgross_salary\x18\x01 \x01(\x01R\vgrossSalary\x12\x1d\n" +
	"\n" +
	"net_salary\x18\x02 \x01(\x01R\tnetSalary\x12\x1e\n" +
	"\n" +
	"deductions\x18\x03 \x01(\x01R\n" +
	"deductions2\x87\x01\n" +
	"\aPayroll\x12|\n" +
	"\x10CalculatePayroll\x12#.payroll.v1.CalculatePayrollRequest\x1a!.payroll.v1.CalculatePayrollReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/payroll/calculateB\x19Z\x17myapp/api/payroll/v1;v1b\x06proto3"

var (
	file_api_payroll_v1_payroll_proto_rawDescOnce sync.Once
	file_api_payroll_v1_payroll_proto_rawDescData []byte
)

func file_api_payroll_v1_payroll_proto_rawDescGZIP() []byte {
	file_api_payroll_v1_payroll_proto_rawDescOnce.Do(func() {
		file_api_payroll_v1_payroll_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_payroll_v1_payroll_proto_rawDesc), len(file_api_payroll_v1_payroll_proto_rawDesc)))
	})
	return file_api_payroll_v1_payroll_proto_rawDescData
}

var file_api_payroll_v1_payroll_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_payroll_v1_payroll_proto_goTypes = []any{
	(*CalculatePayrollRequest)(nil), // 0: payroll.v1.CalculatePayrollRequest
	(*CalculatePayrollReply)(nil),   // 1: payroll.v1.CalculatePayrollReply
}
var file_api_payroll_v1_payroll_proto_depIdxs = []int32{
	0, // 0: payroll.v1.Payroll.CalculatePayroll:input_type -> payroll.v1.CalculatePayrollRequest
	1, // 1: payroll.v1.Payroll.CalculatePayroll:output_type -> payroll.v1.CalculatePayrollReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_payroll_v1_payroll_proto_init() }
func file_api_payroll_v1_payroll_proto_init() {
	if File_api_payroll_v1_payroll_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_payroll_v1_payroll_proto_rawDesc), len(file_api_payroll_v1_payroll_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_payroll_v1_payroll_proto_goTypes,
		DependencyIndexes: file_api_payroll_v1_payroll_proto_depIdxs,
		MessageInfos:      file_api_payroll_v1_payroll_proto_msgTypes,
	}.Build()
	File_api_payroll_v1_payroll_proto = out.File
	file_api_payroll_v1_payroll_proto_goTypes = nil
	file_api_payroll_v1_payroll_proto_depIdxs = nil
}
