// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/payroll/v1/payroll.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Payroll_CalculatePayroll_FullMethodName = "/payroll.v1.Payroll/CalculatePayroll"
	Payroll_ExportPayrollPDF_FullMethodName = "/payroll.v1.Payroll/ExportPayrollPDF"
	Payroll_SendPayslipEmail_FullMethodName = "/payroll.v1.Payroll/SendPayslipEmail"
)

// PayrollClient is the client API for Payroll service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PayrollClient interface {
	CalculatePayroll(ctx context.Context, in *CalculatePayrollRequest, opts ...grpc.CallOption) (*CalculatePayrollReply, error)
	ExportPayrollPDF(ctx context.Context, in *ExportPayrollPDFRequest, opts ...grpc.CallOption) (*ExportPayrollPDFReply, error)
	SendPayslipEmail(ctx context.Context, in *SendPayslipEmailRequest, opts ...grpc.CallOption) (*SendPayslipEmailReply, error)
}

type payrollClient struct {
	cc grpc.ClientConnInterface
}

func NewPayrollClient(cc grpc.ClientConnInterface) PayrollClient {
	return &payrollClient{cc}
}

func (c *payrollClient) CalculatePayroll(ctx context.Context, in *CalculatePayrollRequest, opts ...grpc.CallOption) (*CalculatePayrollReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculatePayrollReply)
	err := c.cc.Invoke(ctx, Payroll_CalculatePayroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payrollClient) ExportPayrollPDF(ctx context.Context, in *ExportPayrollPDFRequest, opts ...grpc.CallOption) (*ExportPayrollPDFReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportPayrollPDFReply)
	err := c.cc.Invoke(ctx, Payroll_ExportPayrollPDF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payrollClient) SendPayslipEmail(ctx context.Context, in *SendPayslipEmailRequest, opts ...grpc.CallOption) (*SendPayslipEmailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendPayslipEmailReply)
	err := c.cc.Invoke(ctx, Payroll_SendPayslipEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayrollServer is the server API for Payroll service.
// All implementations must embed UnimplementedPayrollServer
// for forward compatibility.
type PayrollServer interface {
	CalculatePayroll(context.Context, *CalculatePayrollRequest) (*CalculatePayrollReply, error)
	ExportPayrollPDF(context.Context, *ExportPayrollPDFRequest) (*ExportPayrollPDFReply, error)
	SendPayslipEmail(context.Context, *SendPayslipEmailRequest) (*SendPayslipEmailReply, error)
	mustEmbedUnimplementedPayrollServer()
}

// UnimplementedPayrollServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPayrollServer struct{}

func (UnimplementedPayrollServer) CalculatePayroll(context.Context, *CalculatePayrollRequest) (*CalculatePayrollReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculatePayroll not implemented")
}
func (UnimplementedPayrollServer) ExportPayrollPDF(context.Context, *ExportPayrollPDFRequest) (*ExportPayrollPDFReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportPayrollPDF not implemented")
}
func (UnimplementedPayrollServer) SendPayslipEmail(context.Context, *SendPayslipEmailRequest) (*SendPayslipEmailReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SendPayslipEmail not implemented")
}
func (UnimplementedPayrollServer) mustEmbedUnimplementedPayrollServer() {}
func (UnimplementedPayrollServer) testEmbeddedByValue()                 {}

// UnsafePayrollServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PayrollServer will
// result in compilation errors.
type UnsafePayrollServer interface {
	mustEmbedUnimplementedPayrollServer()
}

func RegisterPayrollServer(s grpc.ServiceRegistrar, srv PayrollServer) {
	// If the following call panics, it indicates UnimplementedPayrollServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Payroll_ServiceDesc, srv)
}

func _Payroll_CalculatePayroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculatePayrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayrollServer).CalculatePayroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payroll_CalculatePayroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayrollServer).CalculatePayroll(ctx, req.(*CalculatePayrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payroll_ExportPayrollPDF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportPayrollPDFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayrollServer).ExportPayrollPDF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payroll_ExportPayrollPDF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayrollServer).ExportPayrollPDF(ctx, req.(*ExportPayrollPDFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payroll_SendPayslipEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPayslipEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayrollServer).SendPayslipEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payroll_SendPayslipEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayrollServer).SendPayslipEmail(ctx, req.(*SendPayslipEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Payroll_ServiceDesc is the grpc.ServiceDesc for Payroll service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Payroll_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payroll.v1.Payroll",
	HandlerType: (*PayrollServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculatePayroll",
			Handler:    _Payroll_CalculatePayroll_Handler,
		},
		{
			MethodName: "ExportPayrollPDF",
			Handler:    _Payroll_ExportPayrollPDF_Handler,
		},
		{
			MethodName: "SendPayslipEmail",
			Handler:    _Payroll_SendPayslipEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/payroll/v1/payroll.proto",
}
