// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.21.12
// source: api/payroll/v1/payroll.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPayrollCalculatePayroll = "/payroll.v1.Payroll/CalculatePayroll"

type PayrollHTTPServer interface {
	CalculatePayroll(context.Context, *CalculatePayrollRequest) (*CalculatePayrollReply, error)
}

func RegisterPayrollHTTPServer(s *http.Server, srv PayrollHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/payroll/calculate", _Payroll_CalculatePayroll0_HTTP_Handler(srv))
}

func _Payroll_CalculatePayroll0_HTTP_Handler(srv PayrollHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CalculatePayrollRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPayrollCalculatePayroll)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CalculatePayroll(ctx, req.(*CalculatePayrollRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CalculatePayrollReply)
		return ctx.Result(200, reply)
	}
}

type PayrollHTTPClient interface {
	CalculatePayroll(ctx context.Context, req *CalculatePayrollRequest, opts ...http.CallOption) (rsp *CalculatePayrollReply, err error)
}

type PayrollHTTPClientImpl struct {
	cc *http.Client
}

func NewPayrollHTTPClient(client *http.Client) PayrollHTTPClient {
	return &PayrollHTTPClientImpl{client}
}

func (c *PayrollHTTPClientImpl) CalculatePayroll(ctx context.Context, in *CalculatePayrollRequest, opts ...http.CallOption) (*CalculatePayrollReply, error) {
	var out CalculatePayrollReply
	pattern := "/v1/payroll/calculate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPayrollCalculatePayroll))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
