// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/payroll/v1/payroll.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExportPayrollPDFRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    uint32                 `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	MonthYear     string                 `protobuf:"bytes,2,opt,name=month_year,json=monthYear,proto3" json:"month_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportPayrollPDFRequest) Reset() {
	*x = ExportPayrollPDFRequest{}
	mi := &file_api_payroll_v1_payroll_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportPayrollPDFRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportPayrollPDFRequest) ProtoMessage() {}

func (x *ExportPayrollPDFRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payroll_v1_payroll_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportPayrollPDFRequest.ProtoReflect.Descriptor instead.
func (*ExportPayrollPDFRequest) Descriptor() ([]byte, []int) {
	return file_api_payroll_v1_payroll_proto_rawDescGZIP(), []int{0}
}

func (x *ExportPayrollPDFRequest) GetEmployeeId() uint32 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *ExportPayrollPDFRequest) GetMonthYear() string {
	if x != nil {
		return x.MonthYear
	}
	return ""
}

type ExportPayrollPDFReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PdfData       []byte                 `protobuf:"bytes,1,opt,name=pdf_data,json=pdfData,proto3" json:"pdf_data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportPayrollPDFReply) Reset() {
	*x = ExportPayrollPDFReply{}
	mi := &file_api_payroll_v1_payroll_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportPayrollPDFReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportPayrollPDFReply) ProtoMessage() {}

func (x *ExportPayrollPDFReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_payroll_v1_payroll_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportPayrollPDFReply.ProtoReflect.Descriptor instead.
func (*ExportPayrollPDFReply) Descriptor() ([]byte, []int) {
	return file_api_payroll_v1_payroll_proto_rawDescGZIP(), []int{1}
}

func (x *ExportPayrollPDFReply) GetPdfData() []byte {
	if x != nil {
		return x.PdfData
	}
	return nil
}

func (x *ExportPayrollPDFReply) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type CalculatePayrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    uint32                 `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	Allowances    float64                `protobuf:"fixed64,2,opt,name=allowances,proto3" json:"allowances,omitempty"`
	MonthYear     string                 `protobuf:"bytes,3,opt,name=month_year,json=monthYear,proto3" json:"month_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculatePayrollRequest) Reset() {
	*x = CalculatePayrollRequest{}
	mi := &file_api_payroll_v1_payroll_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePayrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePayrollRequest) ProtoMessage() {}

func (x *CalculatePayrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payroll_v1_payroll_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePayrollRequest.ProtoReflect.Descriptor instead.
func (*CalculatePayrollRequest) Descriptor() ([]byte, []int) {
	return file_api_payroll_v1_payroll_proto_rawDescGZIP(), []int{2}
}

func (x *CalculatePayrollRequest) GetEmployeeId() uint32 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *CalculatePayrollRequest) GetAllowances() float64 {
	if x != nil {
		return x.Allowances
	}
	return 0
}

func (x *CalculatePayrollRequest) GetMonthYear() string {
	if x != nil {
		return x.MonthYear
	}
	return ""
}

type CalculatePayrollReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrossSalary   float64                `protobuf:"fixed64,1,opt,name=gross_salary,json=grossSalary,proto3" json:"gross_salary,omitempty"`
	NetSalary     float64                `protobuf:"fixed64,2,opt,name=net_salary,json=netSalary,proto3" json:"net_salary,omitempty"`
	Deductions    float64                `protobuf:"fixed64,3,opt,name=deductions,proto3" json:"deductions,omitempty"`
	WorkingDays   int32                  `protobuf:"varint,4,opt,name=working_days,json=workingDays,proto3" json:"working_days,omitempty"`
	OvertimeHours float64                `protobuf:"fixed64,5,opt,name=overtime_hours,json=overtimeHours,proto3" json:"overtime_hours,omitempty"`
	LeaveDays     int32                  `protobuf:"varint,6,opt,name=leave_days,json=leaveDays,proto3" json:"leave_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculatePayrollReply) Reset() {
	*x = CalculatePayrollReply{}
	mi := &file_api_payroll_v1_payroll_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePayrollReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePayrollReply) ProtoMessage() {}

func (x *CalculatePayrollReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_payroll_v1_payroll_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePayrollReply.ProtoReflect.Descriptor instead.
func (*CalculatePayrollReply) Descriptor() ([]byte, []int) {
	return file_api_payroll_v1_payroll_proto_rawDescGZIP(), []int{3}
}

func (x *CalculatePayrollReply) GetGrossSalary() float64 {
	if x != nil {
		return x.GrossSalary
	}
	return 0
}

func (x *CalculatePayrollReply) GetNetSalary() float64 {
	if x != nil {
		return x.NetSalary
	}
	return 0
}

func (x *CalculatePayrollReply) GetDeductions() float64 {
	if x != nil {
		return x.Deductions
	}
	return 0
}

func (x *CalculatePayrollReply) GetWorkingDays() int32 {
	if x != nil {
		return x.WorkingDays
	}
	return 0
}

func (x *CalculatePayrollReply) GetOvertimeHours() float64 {
	if x != nil {
		return x.OvertimeHours
	}
	return 0
}

func (x *CalculatePayrollReply) GetLeaveDays() int32 {
	if x != nil {
		return x.LeaveDays
	}
	return 0
}

type GetPayrollsByMonthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    uint32                 `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	Allowances    float64                `protobuf:"fixed64,2,opt,name=allowances,proto3" json:"allowances,omitempty"`
	MonthYear     string                 `protobuf:"bytes,3,opt,name=month_year,json=monthYear,proto3" json:"month_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayrollsByMonthRequest) Reset() {
	*x = GetPayrollsByMonthRequest{}
	mi := &file_api_payroll_v1_payroll_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayrollsByMonthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayrollsByMonthRequest) ProtoMessage() {}

func (x *GetPayrollsByMonthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payroll_v1_payroll_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayrollsByMonthRequest.ProtoReflect.Descriptor instead.
func (*GetPayrollsByMonthRequest) Descriptor() ([]byte, []int) {
	return file_api_payroll_v1_payroll_proto_rawDescGZIP(), []int{4}
}

func (x *GetPayrollsByMonthRequest) GetEmployeeId() uint32 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *GetPayrollsByMonthRequest) GetAllowances() float64 {
	if x != nil {
		return x.Allowances
	}
	return 0
}

func (x *GetPayrollsByMonthRequest) GetMonthYear() string {
	if x != nil {
		return x.MonthYear
	}
	return ""
}

type PayrollItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrossSalary   float64                `protobuf:"fixed64,1,opt,name=gross_salary,json=grossSalary,proto3" json:"gross_salary,omitempty"`
	NetSalary     float64                `protobuf:"fixed64,2,opt,name=net_salary,json=netSalary,proto3" json:"net_salary,omitempty"`
	Deductions    float64                `protobuf:"fixed64,3,opt,name=deductions,proto3" json:"deductions,omitempty"`
	WorkingDays   int32                  `protobuf:"varint,4,opt,name=working_days,json=workingDays,proto3" json:"working_days,omitempty"`
	OvertimeHours float64                `protobuf:"fixed64,5,opt,name=overtime_hours,json=overtimeHours,proto3" json:"overtime_hours,omitempty"`
	LeaveDays     int32                  `protobuf:"varint,6,opt,name=leave_days,json=leaveDays,proto3" json:"leave_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayrollItem) Reset() {
	*x = PayrollItem{}
	mi := &file_api_payroll_v1_payroll_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayrollItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayrollItem) ProtoMessage() {}

func (x *PayrollItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_payroll_v1_payroll_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayrollItem.ProtoReflect.Descriptor instead.
func (*PayrollItem) Descriptor() ([]byte, []int) {
	return file_api_payroll_v1_payroll_proto_rawDescGZIP(), []int{5}
}

func (x *PayrollItem) GetGrossSalary() float64 {
	if x != nil {
		return x.GrossSalary
	}
	return 0
}

func (x *PayrollItem) GetNetSalary() float64 {
	if x != nil {
		return x.NetSalary
	}
	return 0
}

func (x *PayrollItem) GetDeductions() float64 {
	if x != nil {
		return x.Deductions
	}
	return 0
}

func (x *PayrollItem) GetWorkingDays() int32 {
	if x != nil {
		return x.WorkingDays
	}
	return 0
}

func (x *PayrollItem) GetOvertimeHours() float64 {
	if x != nil {
		return x.OvertimeHours
	}
	return 0
}

func (x *PayrollItem) GetLeaveDays() int32 {
	if x != nil {
		return x.LeaveDays
	}
	return 0
}

type GetPayrollsByMonthReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PayrollItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayrollsByMonthReply) Reset() {
	*x = GetPayrollsByMonthReply{}
	mi := &file_api_payroll_v1_payroll_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayrollsByMonthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayrollsByMonthReply) ProtoMessage() {}

func (x *GetPayrollsByMonthReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_payroll_v1_payroll_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayrollsByMonthReply.ProtoReflect.Descriptor instead.
func (*GetPayrollsByMonthReply) Descriptor() ([]byte, []int) {
	return file_api_payroll_v1_payroll_proto_rawDescGZIP(), []int{6}
}

func (x *GetPayrollsByMonthReply) GetItems() []*PayrollItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type SendPayslipEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    uint32                 `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	MonthYear     string                 `protobuf:"bytes,2,opt,name=month_year,json=monthYear,proto3" json:"month_year,omitempty"`
	ToEmail       string                 `protobuf:"bytes,3,opt,name=to_email,json=toEmail,proto3" json:"to_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPayslipEmailRequest) Reset() {
	*x = SendPayslipEmailRequest{}
	mi := &file_api_payroll_v1_payroll_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPayslipEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPayslipEmailRequest) ProtoMessage() {}

func (x *SendPayslipEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payroll_v1_payroll_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPayslipEmailRequest.ProtoReflect.Descriptor instead.
func (*SendPayslipEmailRequest) Descriptor() ([]byte, []int) {
	return file_api_payroll_v1_payroll_proto_rawDescGZIP(), []int{7}
}

func (x *SendPayslipEmailRequest) GetEmployeeId() uint32 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *SendPayslipEmailRequest) GetMonthYear() string {
	if x != nil {
		return x.MonthYear
	}
	return ""
}

func (x *SendPayslipEmailRequest) GetToEmail() string {
	if x != nil {
		return x.ToEmail
	}
	return ""
}

type SendPayslipEmailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPayslipEmailReply) Reset() {
	*x = SendPayslipEmailReply{}
	mi := &file_api_payroll_v1_payroll_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPayslipEmailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPayslipEmailReply) ProtoMessage() {}

func (x *SendPayslipEmailReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_payroll_v1_payroll_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPayslipEmailReply.ProtoReflect.Descriptor instead.
func (*SendPayslipEmailReply) Descriptor() ([]byte, []int) {
	return file_api_payroll_v1_payroll_proto_rawDescGZIP(), []int{8}
}

func (x *SendPayslipEmailReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_payroll_v1_payroll_proto protoreflect.FileDescriptor

const file_api_payroll_v1_payroll_proto_rawDesc = "" +
	"\n" +
	"\x1capi/payroll/v1/payroll.proto\x12\n" +
	"payroll.v1\x1a\x1cgoogle/api/annotations.proto\"Y\n" +
	"\x17ExportPayrollPDFRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\rR\n" +
	"employeeId\x12\x1d\n" +
	"\n" +
	"month_year\x18\x02 \x01(\tR\tmonthYear\"N\n" +
	"\x15ExportPayrollPDFReply\x12\x19\n" +
	"\bpdf_data\x18\x01 \x01(\fR\apdfData\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"y\n" +
	"\x17CalculatePayrollRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\rR\n" +
	"employeeId\x12\x1e\n" +
	"\n" +
	"allowances\x18\x02 \x01(\x01R\n" +
	"allowances\x12\x1d\n" +
	"\n" +
	"month_year\x18\x03 \x01(\tR\tmonthYear\"\xe2\x01\n" +
	"\x15CalculatePayrollReply\x12!\n" +
	"\fgross_salary\x18\x01 \x01(\x01R\vgrossSalary\x12\x1d\n" +
	"\n" +
	"net_salary\x18\x02 \x01(\x01R\tnetSalary\x12\x1e\n" +
	"\n" +
	"deductions\x18\x03 \x01(\x01R\n" +
	"deductions\x12!\n" +
	"\fworking_days\x18\x04 \x01(\x05R\vworkingDays\x12%\n" +
	"\x0eovertime_hours\x18\x05 \x01(\x01R\rovertimeHours\x12\x1d\n" +
	"\n" +
	"leave_days\x18\x06 \x01(\x05R\tleaveDays\"{\n" +
	"\x19GetPayrollsByMonthRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\rR\n" +
	"employeeId\x12\x1e\n" +
	"\n" +
	"allowances\x18\x02 \x01(\x01R\n" +
	"allowances\x12\x1d\n" +
	"\n" +
	"month_year\x18\x03 \x01(\tR\tmonthYear\"\xd8\x01\n" +
	"\vPayrollItem\x12!\n" +
	"\fgross_salary\x18\x01 \x01(\x01R\vgrossSalary\x12\x1d\n" +
	"\n" +
	"net_salary\x18\x02 \x01(\x01R\tnetSalary\x12\x1e\n" +
	"\n" +
	"deductions\x18\x03 \x01(\x01R\n" +
	"deductions\x12!\n" +
	"\fworking_days\x18\x04 \x01(\x05R\vworkingDays\x12%\n" +
	"\x0eovertime_hours\x18\x05 \x01(\x01R\rovertimeHours\x12\x1d\n" +
	"\n" +
	"leave_days\x18\x06 \x01(\x05R\tleaveDays\"H\n" +
	"\x17GetPayrollsByMonthReply\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.payroll.v1.PayrollItemR\x05items\"t\n" +
	"\x17SendPayslipEmailRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\rR\n" +
	"employeeId\x12\x1d\n" +
	"\n" +
	"month_year\x18\x02 \x01(\tR\tmonthYear\x12\x19\n" +
	"\bto_email\x18\x03 \x01(\tR\atoEmail\"1\n" +
	"\x15SendPayslipEmailReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xa2\x03\n" +
	"\aPayroll\x12|\n" +
	"\x10CalculatePayroll\x12#.payroll.v1.CalculatePayrollRequest\x1a!.payroll.v1.CalculatePayrollReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/payroll/calculate\x12\x99\x01\n" +
	"\x10ExportPayrollPDF\x12#.payroll.v1.ExportPayrollPDFRequest\x1a!.payroll.v1.ExportPayrollPDFReply\"=\x82\xd3\xe4\x93\x027b\x01*\x122/v1/payroll/{employee_id}/payslip/{month_year}.pdf\x12}\n" +
	"\x10SendPayslipEmail\x12#.payroll.v1.SendPayslipEmailRequest\x1a!.payroll.v1.SendPayslipEmailReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/payroll/send-emailB\x19Z\x17myapp/api/payroll/v1;v1b\x06proto3"

var (
	file_api_payroll_v1_payroll_proto_rawDescOnce sync.Once
	file_api_payroll_v1_payroll_proto_rawDescData []byte
)

func file_api_payroll_v1_payroll_proto_rawDescGZIP() []byte {
	file_api_payroll_v1_payroll_proto_rawDescOnce.Do(func() {
		file_api_payroll_v1_payroll_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_payroll_v1_payroll_proto_rawDesc), len(file_api_payroll_v1_payroll_proto_rawDesc)))
	})
	return file_api_payroll_v1_payroll_proto_rawDescData
}

var file_api_payroll_v1_payroll_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_payroll_v1_payroll_proto_goTypes = []any{
	(*ExportPayrollPDFRequest)(nil),   // 0: payroll.v1.ExportPayrollPDFRequest
	(*ExportPayrollPDFReply)(nil),     // 1: payroll.v1.ExportPayrollPDFReply
	(*CalculatePayrollRequest)(nil),   // 2: payroll.v1.CalculatePayrollRequest
	(*CalculatePayrollReply)(nil),     // 3: payroll.v1.CalculatePayrollReply
	(*GetPayrollsByMonthRequest)(nil), // 4: payroll.v1.GetPayrollsByMonthRequest
	(*PayrollItem)(nil),               // 5: payroll.v1.PayrollItem
	(*GetPayrollsByMonthReply)(nil),   // 6: payroll.v1.GetPayrollsByMonthReply
	(*SendPayslipEmailRequest)(nil),   // 7: payroll.v1.SendPayslipEmailRequest
	(*SendPayslipEmailReply)(nil),     // 8: payroll.v1.SendPayslipEmailReply
}
var file_api_payroll_v1_payroll_proto_depIdxs = []int32{
	5, // 0: payroll.v1.GetPayrollsByMonthReply.items:type_name -> payroll.v1.PayrollItem
	2, // 1: payroll.v1.Payroll.CalculatePayroll:input_type -> payroll.v1.CalculatePayrollRequest
	0, // 2: payroll.v1.Payroll.ExportPayrollPDF:input_type -> payroll.v1.ExportPayrollPDFRequest
	7, // 3: payroll.v1.Payroll.SendPayslipEmail:input_type -> payroll.v1.SendPayslipEmailRequest
	3, // 4: payroll.v1.Payroll.CalculatePayroll:output_type -> payroll.v1.CalculatePayrollReply
	1, // 5: payroll.v1.Payroll.ExportPayrollPDF:output_type -> payroll.v1.ExportPayrollPDFReply
	8, // 6: payroll.v1.Payroll.SendPayslipEmail:output_type -> payroll.v1.SendPayslipEmailReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_payroll_v1_payroll_proto_init() }
func file_api_payroll_v1_payroll_proto_init() {
	if File_api_payroll_v1_payroll_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_payroll_v1_payroll_proto_rawDesc), len(file_api_payroll_v1_payroll_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_payroll_v1_payroll_proto_goTypes,
		DependencyIndexes: file_api_payroll_v1_payroll_proto_depIdxs,
		MessageInfos:      file_api_payroll_v1_payroll_proto_msgTypes,
	}.Build()
	File_api_payroll_v1_payroll_proto = out.File
	file_api_payroll_v1_payroll_proto_goTypes = nil
	file_api_payroll_v1_payroll_proto_depIdxs = nil
}
