// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/employee/v1/employee.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_employee_v1_employee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_employee_v1_employee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_employee_v1_employee_proto_rawDescGZIP(), []int{0}
}

type ListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReply) Reset() {
	*x = ListReply{}
	mi := &file_api_employee_v1_employee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReply) ProtoMessage() {}

func (x *ListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_employee_v1_employee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReply.ProtoReflect.Descriptor instead.
func (*ListReply) Descriptor() ([]byte, []int) {
	return file_api_employee_v1_employee_proto_rawDescGZIP(), []int{1}
}

var File_api_employee_v1_employee_proto protoreflect.FileDescriptor

const file_api_employee_v1_employee_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/employee/v1/employee.proto\x12\vemployee.v1\x1a\x1cgoogle/api/annotations.proto\"\r\n" +
	"\vListRequest\"\v\n" +
	"\tListReply2X\n" +
	"\bEmployee\x12L\n" +
	"\x04List\x12\x18.employee.v1.ListRequest\x1a\x16.employee.v1.ListReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/employeesB\x1aZ\x18myapp/api/employee/v1;v1b\x06proto3"

var (
	file_api_employee_v1_employee_proto_rawDescOnce sync.Once
	file_api_employee_v1_employee_proto_rawDescData []byte
)

func file_api_employee_v1_employee_proto_rawDescGZIP() []byte {
	file_api_employee_v1_employee_proto_rawDescOnce.Do(func() {
		file_api_employee_v1_employee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_employee_v1_employee_proto_rawDesc), len(file_api_employee_v1_employee_proto_rawDesc)))
	})
	return file_api_employee_v1_employee_proto_rawDescData
}

var file_api_employee_v1_employee_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_employee_v1_employee_proto_goTypes = []any{
	(*ListRequest)(nil), // 0: employee.v1.ListRequest
	(*ListReply)(nil),   // 1: employee.v1.ListReply
}
var file_api_employee_v1_employee_proto_depIdxs = []int32{
	0, // 0: employee.v1.Employee.List:input_type -> employee.v1.ListRequest
	1, // 1: employee.v1.Employee.List:output_type -> employee.v1.ListReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_employee_v1_employee_proto_init() }
func file_api_employee_v1_employee_proto_init() {
	if File_api_employee_v1_employee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_employee_v1_employee_proto_rawDesc), len(file_api_employee_v1_employee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_employee_v1_employee_proto_goTypes,
		DependencyIndexes: file_api_employee_v1_employee_proto_depIdxs,
		MessageInfos:      file_api_employee_v1_employee_proto_msgTypes,
	}.Build()
	File_api_employee_v1_employee_proto = out.File
	file_api_employee_v1_employee_proto_goTypes = nil
	file_api_employee_v1_employee_proto_depIdxs = nil
}
